# Build to docker hub : hub.docker.com

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
  script:
    - docker build --tag $DOCKERHUB_REGISTRY_IMAGE:latest -f Dockerfile .
    - docker push $DOCKERHUB_REGISTRY_IMAGE:latest
  only:
    - main

# deploy: See in folder gitlab for deploy script