stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  # Specify a Docker image to run the job in.
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main # branch name

deploy:
  stage: deploy
  image: cylab/kubectl
  before_script:
    # create the configuration (context) for our kubernetes cluster
    - kubectl config set-cluster deploy-cluster --server="$K8S_SERVER" --insecure-skip-tls-verify
    - kubectl config set-credentials gitlab --token=$(echo $K8S_TOKEN | base64 -d)
    - kubectl config set-context deploy-cluster --cluster=deploy-cluster --namespace=default --user=gitlab
    - kubectl config use-context deploy-cluster
  script:
    - kubectl apply -f kubernetes/app/app-deploy.yaml
    - kubectl rollout restart deploy app-deploy-name # Change app-deploy-name to your deployment name $ kubectl get deployments
  only:
    - main # branch name
