apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: app-deploy
  template:
    metadata:
      labels:
        name: app-deploy
    spec:
      imagePullSecrets:
        - name: xxxx-token # Change this with your registry hosting, ex : github-token, gitlab-token, dockerhub-token
      containers:
        - name: app-deploy
          # image: docker.io/<username>/<repository>:latest
          # image: registry.gitlab.com/<username>/<repository>:latest
          image: ghcr.io/<username>/<repository>:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 1
            initialDelaySeconds: 45
          env:
            - name: STARTUP_DELAY_SECONDS
              value: "40"
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    name: app-deploy
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  # externalTrafficPolicy: Cluster
  # type: LoadBalancer
