apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: nextjs-tls
      hosts:
        - next.cic-webpro.com
    # - secretName: service2-tls
    #   hosts:
    #     - service2.cic-webpro.com
  rules:
    - host: next.cic-webpro.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 80
    # - host: service2.cic-webpro.com
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: app-service-two
    #             port:
    #               number: 80
